---
- name: Install common packages
  become: yes
  apt:
    name: "{{ common_packages }}"
    state: present
    install_recommends: no
    update_cache: yes

- name: Get env variables
  become: no
  setup:
    filter:
      - "ansible_env"

- name: Copy bash_aliases
  become: no
  copy:
    src: "bash_aliases"
    dest: "{{ ansible_env.HOME }}/.bash_aliases"
    mode: 0644
    backup: no
