version: '3.8'
services:
  ansible:
    image: local/ansible:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ansible
    volumes:
      - .:/ansible
    working_dir: /ansible
    command: ash
    stdin_open: true
    tty: true
    networks:
      public_net:
        ipv4_address: 192.168.80.130
networks:
  public_net:
    driver: bridge
    name: ansible-public-net
    ipam:
      config:
        - subnet: 192.168.80.128/26
    driver_opts:
      com.docker.network.bridge.name: 'br-ansible'
